/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define PERIPHERAL_BASE (0x40000000U)
#define AHB1_PERIPH_OFFSET (0x20000U)
#define AHB1_BASE (PERIPHERAL_BASE + AHB1_PERIPH_OFFSET)

#define RCC_AHB1_OFFSET (0x3800U)
#define RCC_BASE (AHB1_BASE + RCC_AHB1_OFFSET)
#define RCC_AHB1_EN_R_OFFSET (0x30U)
#define RCC_AHB1_EN_R *((uint32_t *)(RCC_BASE + RCC_AHB1_EN_R_OFFSET))
#define GPIOA_ENABLE_BIT (1U << 0)
#define GPIOC_ENABLE_BIT (1U << 2)
#define GPIOD_ENABLE_BIT (1U << 3)

#define GPIOA_AHB1_OFFSET (0x0U)
#define GPIOA_BASE (AHB1_BASE + GPIOA_AHB1_OFFSET)

#define GPIOC_AHB1_OFFSET (0x800U)
#define GPIOC_BASE (AHB1_BASE + GPIOC_AHB1_OFFSET)

#define GPIOD_AHB1_OFFSET (0xC00U)
#define GPIOD_BASE (AHB1_BASE + GPIOD_AHB1_OFFSET)

#define MODE_R_OFFSET (0x00U)
#define GPIOC_MODE_R *((uint32_t *)(GPIOC_BASE + MODE_R_OFFSET))
#define GPIOD_MODE_R *((uint32_t *)(GPIOD_BASE + MODE_R_OFFSET))

#define OD_R_OFFSET (0x14U)
#define GPIOC_OD_R *((uint32_t *)(GPIOC_BASE + OD_R_OFFSET))
#define GPIOD_OD_R *((uint32_t *)(GPIOD_BASE + OD_R_OFFSET))

#define ID_R_OFFSET (0x10U)
#define GPIOA_ID_R *((uint32_t *)(GPIOA_BASE + ID_R_OFFSET))
#define GPIOC_ID_R *((uint32_t *)(GPIOC_BASE + ID_R_OFFSET))
#define GPIOD_ID_R *((uint32_t *)(GPIOD_BASE + ID_R_OFFSET))

#define PUP_D_R_OFFSET (0x0CU)
// #define GPIOC_PUP_D_R

// PC 4 - 11 -- LEDS

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void mode_setup() {
	// 8 leds
	// moder for pc4 = 01 - output mode
	GPIOC_MODE_R |= (1U << 8);
	GPIOC_MODE_R &= ~(1U << 9);
	// pc5 output
	GPIOC_MODE_R |= (1U << 10);
	GPIOC_MODE_R &= ~(1U << 11);
	// pc6 output
	GPIOC_MODE_R |= (1U << 12);
	GPIOC_MODE_R &= ~(1U << 13);
	// pc7 output
	GPIOC_MODE_R |= (1U << 14);
	GPIOC_MODE_R &= ~(1U << 15);
	// pc8 output
	GPIOC_MODE_R |= (1U << 16);
	GPIOC_MODE_R &= ~(1U << 17);
	// pc9 output
	GPIOC_MODE_R |= (1U << 18);
	GPIOC_MODE_R &= ~(1U << 19);
	// pc10 output
	GPIOC_MODE_R |= (1U << 20);
	GPIOC_MODE_R &= ~(1U << 21);
	// pc11 output
	GPIOC_MODE_R |= (1U << 22);
	GPIOC_MODE_R &= ~(1U << 23);

	// button
	// pd2, pc13 - input = 00 - reset state

}

// pd2 - sw - red button
// pc13 - blue button
int cnt = 0;

int main(void)
{
	// enable gpioc
	RCC_AHB1_EN_R |= GPIOA_ENABLE_BIT;
    RCC_AHB1_EN_R |= GPIOC_ENABLE_BIT;
    RCC_AHB1_EN_R |= GPIOD_ENABLE_BIT;
    mode_setup();

    /* Loop forever */
	while (1) {
		// if button on pd2:
		    if (!(GPIOD_ID_R & (1U << 2))) {
		        cnt = (cnt + 1) % 8;
		    }
		    if (!(GPIOC_ID_R & (1U << 13))) {
				cnt = (cnt + 7) % 8;
			}
		    switch (cnt) {
		    case 0: {
				GPIOC_OD_R = (1U << 4);
				break;
		    }
		    case 1: {
				GPIOC_OD_R = (1U << 5);
				break;
			}
		    case 2: {
				GPIOC_OD_R = (1U << 6);
				break;
			}
		    case 3: {
				GPIOC_OD_R = (1U << 7);
				break;
			}
		    case 4: {
				GPIOC_OD_R = (1U << 8);
				break;
			}
		    case 5: {
				GPIOC_OD_R = (1U << 9);
				break;
			}
		    case 6: {
				GPIOC_OD_R = (1U << 10);
				break;
			}
		    case 7: {
				GPIOC_OD_R = (1U << 11);
				break;
			}
		    }
		    for (long i = 0; i < 200000; i++);
	}
}
